version: 1.2.0-{build}
image: Visual Studio 2017 RC
pull_requests:
  do_not_increment_build_number: true
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
before_build:
- ps: dotnet restore
build_script:
- dotnet build --configuration Release
- dotnet pack --no-build --configuration Release .\src\CoreFtp\CoreFtp.csproj
test: off
artifacts:
- path: src\CoreFtp\bin\Release\CoreFtp.*.nupkg
